# Uncomment the next line to define a global platform for your project
platform :ios, '16.2'

target 'ex01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ex01

end

target 'ex02' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ex02
  pod 'Alamofire', '~> 4.8.2'
  pod 'ObjectMapper', '~> 3.4.2'
  pod 'RecastAI', '~> 3.5.0'
end


target 'ex03' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ex02
  pod 'Alamofire', '~> 4.8.2'
  pod 'ObjectMapper', '~> 3.4.2'
  pod 'RecastAI', '~> 3.5.0'
end
